services:
  - type: web
    name: flowbee-whatsapp
    env: docker
    plan: free
    dockerFilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_orders
      - key: SHOPIFY_APP_URL
        sync: false
      - key: DATABASE_URL
        value: file:/data/dev.sqlite
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
